name: sync-Squaregentleman/mimotion

on:
  schedule:
  - cron:  "*/15 * * * *"
  workflow_dispatch:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-18.04
    if: ${{ github.event.repository.owner.id == github.event.sender.id && github.repository == 'DoveBoy/mimotion' }}
    timeout-minutes: 2

    steps:
    - name: Init Build Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E rm -rf /etc/apt/sources.list.d
        sudo -E apt-get update -y
        sudo -E apt-get install -y build-essential git git-core curl wget
        sudo -E apt-get clean -y
        git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'

    - name: Prepare
      run: |
        mkdir -p ~/.ssh
        echo -e "${{ secrets.LXKEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitee.com > ~/.ssh/known_hosts

    - name: Clone main
      run: |
        git clone -b main https://github.com/Squaregentleman/mimotion.git main

    - name: Push main
      uses: ad-m/github-push-action@master
      with:
        directory: main
        github_token: ${{ secrets.PAT }}
        branch: main

    # - name: Delete Workflow Runs
      # uses: Mattraks/delete-workflow-runs@main
      # with:
        # token: ${{ github.token }}
        # repository: ${{ github.repository }}
        # retain_days: 1
        # keep_minimum_runs: 0
